name: Daily Website Uptime Check

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest

    steps:
      - name: Check website
        id: check
        run: |
          if curl -fsS https://www.edenjia.com/ > /dev/null; then
            echo "status=ok" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Check website
        id: check
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://www.edenjia.com)

          echo "HTTP status: $STATUS"

          if [ "$STATUS" -ge 500 ] || [ "$STATUS" -eq 000 ]; then
            echo "status=fail" >> $GITHUB_OUTPUT
          else
            echo "status=ok" >> $GITHUB_OUTPUT
          fi